services:
  cart-service:
    build: .
    container_name: cart-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:admin123@shared-postgres:5432/ecommerce_db
      - KAFKA_BOOTSTRAP_SERVERS=shared-kafka:9092
      - DEBUG=true
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    external: true
    name: ecommerce-network